server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ClientAPI
          uri: http://localhost:8081/
          predicates:
            - Path=/main/**, /css/**
        - id: UsersCardTransfer
          uri: http://localhost:8082/
          predicates:
            - Path=/server/**
