spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynewdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
